version: "3.8"

services:
  test_web_2_app:
    container_name: test_web_2_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URL = ./sql_app.db
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    command:
       "pytest -vv"

